project:
  type: website
  resources:
    - "presentations/**/assets/**"
    - "presentations/**/*.png"
    - "presentations/**/*.jpg"
    - "presentations/**/*.jpeg"
    - "presentations/**/*.gif"
    - "presentations/**/*.pdf"
    - "presentations/**/*.mp4"
    - "presentations/**/*.webm"
    - "presentations/**/*.wav"

website:
  title: "Everton Eduardo Colombo"
  description: "Personal Blog"
  site-url: "https://evertoncolombo.github.io/blog/"
  navbar:
    left:
      - text: "Posts"
        href: index.qmd
      - text: "Quotes"
        href: quotes.qmd
      - text: "Datasets"
        href: datasets.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "TIL"
        href: til.qmd
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/EvertonColombo

format:
  html:
    theme:
      light: morph
      dark: cyborg
    toc: true
    css: styles.css